services:
  postgres:
    image: postgres:16
    container_name: sigea_postgres
    restart: always
    environment:
      POSTGRES_USER: sigea
      POSTGRES_PASSWORD: sigea123
      POSTGRES_DB: sigea_db
    ports:
      - "5432:5432"
    volumes:
      - sigea_postgres_data:/var/lib/postgresql/data

volumes:
  sigea_postgres_data:
